import type { Metadata } from 'next'
import { Lato } from 'next/font/google'

import { twm } from '@/utils/twm'

import '@/style/index.scss'
import StoryblokProvider from '@/lib/StoryBlokProvider'

const lato = Lato({
  style: ['normal', 'italic'],
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoryblokProvider>
      <html lang='en'>
        <body
          className={twm(
            'relative isolate w-screen min-h-screen flex-col-center-bottom overflow-x-hidden',
            lato.variable,
            'antialiased'
          )}
        >
          <div className="BG_TEXTURE z-0 fixed top-0 left-0 full-screen bg-[url('/noise-bg.png')]" />
          <div className='PAGE_CONTAINER z-10 w-[var(--reading-content-width)] flex-col-center gap-md'>
            {children}
          </div>
        </body>
      </html>
    </StoryblokProvider>
  )
}
